export const SET_ITEMS="SET_ITEMS"
export const REMOVE_ITEMS="REMOVE_ITEMS"
export const SET_ID="SET_ID"
export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';